[package]
cairo-version = "2.4.0"
name = "stark_sprouts"
version = "0.5.1"

[cairo]
sierra-replace-ids = true

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.5.1" }

[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.env]
rpc_url = "http://localhost:5050/"
# Default account for katana with seed = 0
account_address = "0x6162896d1d7ab204c7ccac6dd5f8e9e7c25ecd5ae4fcb4ad32e57786bb46e03"
private_key = "0x1800000000300000180000000000030000000000003006001800006600"

[tool.dojo.world]
name = "Stark Sprouts"
description = "..."
# cover_uri = "file://assets/cover.png"
# icon_uri = "file://assets/icon.png"
# website = "https://github.com/dojoengine/dojo-starter"

[tool.dojo.world.socials]
x = "https://x.com/starksprouts"
# discord = "https://discord.gg/FB2wR6uF"
# github = "https://github.com/dojoengine/dojo-starter"
# telegram = "https://t.me/dojoengine"
